# Site
repository: fennytrucds/fennytrucds.github.io
favicon: images/favicon.ico

version: 2

# Personal info
name: Fenny Truc
title: Data Scientist
email: ngthtruc1412@gmail.com

# Social links
github_username:  fennytrucds
linkedin_username: fennytruc

# About Section
# about_title: About Me
about_profile_image: images/jg2.jpg
about_content: |
  Hi, my name is James Grant, I'm a Data Scientist with over 6 years of experience in Data Analytics currently specializing in Data Analytics and Statistics.
  I am currently pursuing a master's degree in Applied Statistics at University of Strathclyde.

  I have worked with a range of different languages and frameworks and I am always looking for opportunities to work
  with something new. The things that I currently have the most experience working with are:
  <mark>ES6 Javascript</mark>,
  <mark>React &amp; Redux</mark>,
  <mark>Node.js</mark>,
  <mark>Java</mark>,
  <mark>MySQL</mark>,
  <mark>SASS</mark>,
  <mark>git</mark> and
  <mark>AWS</mark>.

content:
  - title: Projects # Title for the section
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: Modern Resume Theme
        link: sproogen.github.io/modern-resume-theme
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: https://github.com/sproogen/modern-resume-theme
        quote: >
          A modern simple static resume template and theme. Powered by Jekyll and GitHub pages.
        description: |
          This is a <mark>Jekyll</mark> theme that I have recently created, in fact it is what this resume has been built with.
          I decided I wanted to learn how to create a fully open source project and thought that this would be the perfect project to do this with.
          It has allowed me to share something I have created in a way that will be helpful for lots of people while also learning from this myself.
      - layout: top-middle
        title: itsgoingto.be
        link: www.itsgoingto.be
        additional_links:
          - title: sproogen/itsgoingto.be
            icon: fab fa-github
            url: https://github.com/sproogen/itsgoingto.be
        quote: >
          itsgoingto.be is a simple voting site where a user can ask a question or topic top put to a vote. This question
          can then be shared with their friends/colleagues to vote on things like 'Where should we go for lunch?'.
        description: |
          The API for this site has been build using <mark>Node.js</mark> while the front end is a <mark>React</mark>/<mark>Redux</mark> app.
          I have used <mark>Docker</mark> to set up a development environment and <mark>Heroku</mark> to deploy and host the site. I have
          a suite of unit and API tests for the backend and unit tests for the front end.

          I have been using this project as a way to increase many of my skills and also learn new things, most recently sockets and Node.JS. I have particually
          enjoyed managing my own project and designing my own architecture and implementing this to a high standard.

          Feel free to check out the whole project on GitHub to get a feel for how I work [here](https://github.com/sproogen/itsgoingto.be).

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Zalo (VNG Corporation)
        sub_title: Data Analyst
        caption: Nov 2022 - July 2024
        description: |
          Worked with millions of users behavior data log generated on a daily basis.

          Iteratively building and prototyping ETL data analysis pipelines to provide dashboard (daily/weekly/monthly)
          and monitor product performance. 
          Key features include Lunar New Holiday and Bank Card dashboards. 

          Experienced in identifying and implementing process improvements for data pipelines on Big Data Platforms.



      - layout: left
        border: weak
        title: Saigon A.I.
        sub_title: Data Scientist Analyst
        link: https://www.saigonai.com/
        caption: June 2018 - Aug 2022
        description: |
          Digging deep into the millions of data records to develop, built and trained and tested  machine learning pipelines, implemented and deploy a classification model on production. 
          Communicating and reporting back the performance.

          Selected, built, trained and tested machine learning models (Logistics Regression Classification Model)

          
          Automating the workflow  from gathering multiple sources of data.

          Experimenting with different time-series methods of forecasting models (ARIMA) to forecast sales demand.

          Maintained the main classification model on production.

          Developed advance monthly statistical reports (R Markdown) and performed ad-hoc statistical analysis report to trouble shoot fraudulent cases.

      - layout: left
        border: weak
        title: Simitive
        sub_title: Full Stack Developer
        link: www.simitive.com
        caption: November 2015 - August 2017
        description: |
          During my time at Simitive I worked as part of an agile team building our own in house web based software and
          also a large scale website for an international client. I gained experience working with a continuous integration
          workflow using tools such as <mark>Jenkins</mark> and working with Amazon Web Services for deployments. We built most
          of our software using <mark>Symfony</mark>, <mark>Backbone</mark>, <mark>Marionette</mark>, <mark>Vue</mark> and <mark>Vuex</mark>.

          For 6 months I was working on delivering a standalone web product for an international client that services over
          600,000 users. This has been built from the ground up using <mark>Symfony</mark> to provide a backend API and
          <mark>Backbone</mark> for the front end. I also gained a lot of experience with <mark>Elasticsearch</mark> to provide
          search functionality of millions of entities to the front end. During the project I spent time out of hours
          communicating with the client, performing deployments and providing support.

          Towards the end of my time at Simitive my role involved assisting with the company's devOps, this included managing
          our <mark>AWS</mark> infrastructure as well as deploying and migrating sites. I also spent time configuring and maintaining
          our clients SSO, this mostly involves configuring new clients who are using <mark>AD FS</mark>, <mark>Shibboleth</mark> and
          <mark>CAS</mark> but also maintaining our software's SSO functionality.

      - layout: left
        border: weak
        title: Freelance
        sub_title: Android Development
        caption: September 2016 - October 2016
        description: |
          I was asked to update an existing Android app to the latest version of Android and to fix any issues caused by
          this as well as a few other existing issues. This project had a very tight time scale and I was able to complete
          it in very good time while providing regular updates to the client.

      - layout: left
        border: weak
        title: Nudge Digital
        sub_title: Full Stack Developer
        link: www.nudgedigital.co.uk
        caption: August 2014 - November 2015
        description: |
          While working at Nudge I was able to work on a large number of projects ranging from small Drupal sites to large
          enterprise level applications. I enjoy being able to work with clients to understand and surpass their expectations.
          At Nudge I was also given the oppertunity to work with all of my core skills and to gain new skills in things
          such as <mark>Symfony</mark>, <mark>Angular</mark> and <mark>Gulp</mark>. I also worked on a number of <mark>iOS</mark> and
          <mark>Android</mark> applications.

          During my time at Nudge I was able to help the lead developer with the writing of Technical Specifications and
          also Project Requirements. I feel this is a useful skill to have as it helps me to become an even more well-rounded
          developer.

          During the summer I had the opportunity to head to Accra, Ghana and work with the team out there. This was a
          great opportunity to learn more about the industry in another country but also to allow me to lead their
          team for a few weeks and gain lots of experience of remote teams.

      - layout: left
        title: GWS Media
        sub_title: Web Developer
        link: www.gwsmedia.com
        caption: June 2012 - August 2014
        description: |
          I started working for GWS Media part time during my third year at University and continued full time once I had
          graduated. It was during this role that I learnt many of the fundamentals that I have been building on over
          the past 3 years. Whilst at GWS I had the opportunity to work with:
          <mark>Drupal</mark>, <mark>Magento</mark>, <mark>Bootstrap</mark>, <mark>Codeigniter</mark>, <mark>Android</mark> and <mark>iOS</mark>.

          I feel like having the opportunity to use a large range of different things early on in my career has given me
          the drive to always want to try new tools and frameworks.

  - title: Education
    layout: list
    content:
      - title: University of Strathclyde
        sub_title: MSc in Applied Statistics
        caption: 09/2014 - Ongoing (09/2025)
        description: |
          During my degree at Bristol University I learnt lots of key skills such as team work and project management. Although
          we mainly focused on software development and the principles of programming I use a lot of these skills to
          my advantage in my day to day work.

          While at Bristol Uni I spent a lot of my free time with the Kitesurfing society. I spent 3 years on the committee
          as a secretary, trip rep and then media and promotions manager. During this time I took on roles from organising
          transport and designing posters to organizing a trip to Portugal for over 30 students.

  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I'm not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as
      mountain biking, road cycling, kitesuring and horse riding as well as trying to make time for things like
      rock climbing and playing some rugby. I currently have 2 horses and find this is a great way to get out of the house
      and taking my mind of things while learing to showjump.

      I'm interested in photography and videography as I like to be creative, this is mainly through sport but
      I enjoy landscape and abstract photography too. I like to showcase my work on instagram if
      you would like to take a look - [jameswgrant](https://www.instagram.com/jameswgrant/).

      Finally during the rest of my free time you will either find me working on my bikes, rock climbing at one of
      Bristol's indoor climbing centres or down 'The Rec' supporting Bath Rugby.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed